name: avaremp
description: "NexusEFB branding preview build"
publish_to: 'none'
version: 0.0.106+106

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  win32: ^5.5.3
  path: ^1.8.3
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+1
  flutter_material_design_icons: ^3.1.0+7447
  geolocator: ^14.0.2
  geolocator_linux: ^0.2.0+1
  wakelock_plus: ^1.1.4
  dio: ^5.3.4
  archive: ^4.0.7
  http: any
  exif: ^3.3.0
  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  dropdown_button2: ^2.3.9
  latlong2: ^0.9.0
  auto_size_text: ^3.0.0
  intl: any
  flutter_launcher_icons: ^0.14.4
  introduction_screen: ^3.1.12
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  widget_zoom: ^0.0.3
  xml: ^6.5.0
  flutter_keyboard_visibility: ^6.0.0
  html: ^0.15.4
  image: ^4.1.7
  share_plus: ^11.1.0
  file_picker: ^10.3.1
  image_picker: ^1.1.2
  audioplayers: ^6.5.0
  syncfusion_flutter_pdfviewer: ^30.2.6
  day_night_time_picker: ^1.3.0+1
  fl_chart: ^1.0.0
  point_in_polygon: ^1.0.0
  toastification: ^3.0.3
  in_app_review: ^2.0.10
  scribble: ^0.10.0+1
  value_notifier_tools: ^0.1.2
  geojson_vi: ^2.2.5
  csv: ^5.0.0
  vector_map_tiles: any
  mbtiles: ^0.4.2
  vector_tile_renderer: any
  vector_tile: any
  sqlite3_flutter_libs: any
  universal_io: ^2.2.2
  flutter_bluetooth_serial_ble: ^0.5.0
  msvcredist:
    git:
      url: https://github.com/insertjokehere/flutter_msvcredist.git
      ref: main
  yaml: any
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_ui_auth: ^3.0.1
  firebase_ai: ^3.6.0
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.0.0
  purchases_flutter: ^9.9.9
  purchases_flutter_ui: ^0.0.1
  purchases_ui_flutter: ^9.9.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  msix:
    git:
      url: https://github.com/insertjokehere/msix.git
      ref: msvc_redist
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/branding/
    - assets/docs/
    - pubspec.yaml
    - assets/audio/traffic_alerts/
    - assets/audio/gpws/
    - assets/audio/runway_incursion/

msix_config:
  display_name: NexusEFB
  publisher_display_name: Apps4Av Inc.
  identity_name: Apps4AvInc.AvareX
  publisher: CN=97AA5BF2-3109-4884-8224-A2AB9E6DB29A
  msix_version: 1.0.106.0
  logo_path: assets/images/logo.png
  capabilities: internetClient, location
  store: true
